spring:
  application:
    name: codestagram
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/spring-cafe
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
