spring:
  application:
    name: codestargram

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    hidden-method:
      filter:
        enabled: true

  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    session:
      tracking-modes: cookie